# Generated by Django 3.2.13 on 2022-07-07 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.IntegerField()),
                ('number_of_people', models.IntegerField(default='1', help_text='For parties of more than 10, please call us on 021 4569 782', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('table', models.CharField(choices=[('Window', 'WINDOW'), ('Outside', 'OUTSIDE'), ('Inside', 'INSIDE'), ('Booth', 'BOOTH')], default='Inside', max_length=50)),
                ('occasion', models.CharField(choices=[('Birthday', 'BIRTHDAY'), ('Anniversary', 'ANNIVERSARY'), ('Graduation', 'GRADUATION'), ('Communion', 'COMMUNION'), ('Confirmation', 'CONFIRMATION'), ('Christening', 'CHRISTENING'), ('Date Night', 'DATE NIGHT')], default='Birthday', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booker', models.CharField(max_length=50)),
                ('TableNo', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default='1', max_length=10)),
                ('location', models.CharField(choices=[('Window', 'WINDOW'), ('Outside', 'OUTSIDE'), ('Inside', 'INSIDE'), ('Booth', 'BOOTH')], default='Inside', max_length=10)),
                ('max_pax', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='2', max_length=10)),
            ],
        ),
    ]
