# Generated by Django 4.1.3 on 2022-11-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_booking_booking_number_alter_booking_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_number',
        ),
    ]
