# Generated by Django 3.2.13 on 2022-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(choices=[('Birthday', 'BIRTHDAY'), ('Anniversary', 'ANNIVERSARY'), ('Graduation', 'GRADUATION'), ('Communion', 'COMMUNION'), ('Confirmation', 'CONFIRMATION'), ('Christening', 'CHRISTENING'), ('Date Night', 'DATE NIGHT'), ('Friends Night', 'FRIENDS NIGHT'), ('None', 'None')], default='Birthday', max_length=100),
        ),
    ]
