# Generated by Django 3.2.13 on 2022-07-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_auto_20220706_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.CharField(choices=[('Window', 'WINDOW'), ('Outside', 'OUTSIDE'), ('Inside', 'INSIDE'), ('Booth', 'BOOTH')], default='Inside', max_length=50),
        ),
    ]
