# Generated by Django 3.2.13 on 2022-07-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_alter_booking_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.RemoveField(
            model_name='table',
            name='location',
        ),
    ]
