# Generated by Django 3.2.13 on 2022-08-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0010_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_people',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='<br> For parties of more than 10, please call us on 021 4569 782', max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(choices=[('Birthday', 'BIRTHDAY'), ('Anniversary', 'ANNIVERSARY'), ('Graduation', 'GRADUATION'), ('Communion', 'COMMUNION'), ('Confirmation', 'CONFIRMATION'), ('Christening', 'CHRISTENING'), ('Date Night', 'DATE NIGHT'), ('Friends Night', 'FRIENDS NIGHT'), ('None', 'None')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.CharField(choices=[('Window', 'WINDOW'), ('Outside', 'OUTSIDE'), ('Inside', 'INSIDE'), ('Booth', 'BOOTH')], max_length=50),
        ),
    ]
